function movieMap = preloadVideos(stimulusData, metaData, wPtr)
    movieMap = containers.Map();
    for nTrial = 1:size(stimulusData.fileName, 1)
        for nStimulus = find([stimulusData.isVideo(nTrial, :)])
            movieKey = stimulusData.fileName{nTrial, nStimulus};
            if ~isKey(movieMap, movieKey)
                movieData = struct('textures', [], 'timing', [], ...
                    'movieduration', [], 'fps', [], 'imgw', [], ...
                    'imgh', []);
                [movieData.textures, movieData.timing, ...
                    movieData.movieduration, movieData.fps, ...
                    movieData.imgw, movieData.imgh] = ...
                    bufferVideo(wPtr, ...
                    strjoin({pwd(), stimulusData.fileName{nTrial, nStimulus}}, '/'), ...
                    metaData.bufferSize);
                movieMap(movieKey) = movieData;
            end
        end
    end
end
